import { imagePath } from "./Constant";

export const assetsObj = {
  logo: `${imagePath}images/logo.png`,
  banner_bg_image: `${imagePath}images/banner-bg.png`,
  banner_image: `${imagePath}images/banner-img-1.png`,
  jquery_icon: `${imagePath}images/jquery_icon.png`,
  mongodb_icon: `${imagePath}images/mongodb-icon.png`,
  android_icon: `${imagePath}images/android_icon.png`,
  java_icon: `${imagePath}images/java_icon .png`,
  logo_first_letter: `${imagePath}images/logo-first-letter.png`,
  client_img1: `${imagePath}images/client-serve-img-1.png`,
  client_img2: `${imagePath}images/client-serve-img-2.png`,
  client_img3: `${imagePath}images/client-serve-img-3.png`,
  learning_system_icon: `${imagePath}icon/e-learning_system_icon.png`,
  employment_meeting_icon: `${imagePath}icon/employment_meeting_icon.png`,
  handshake_agreement_icon: `${imagePath}icon/handshake_agreement_icon.png`,
  share_social_icon: `${imagePath}icon/share_social_icon.png`,
  profile_group_icon: `${imagePath}icon/profile_group_icon.png`,
  hireDevImg1: `${imagePath}images/hire-dev-1.png`,
  hireDevImg2: `${imagePath}images/hire-dev-2.png`,
  blueBorderGradient: `${imagePath}images/border-layer-1.png`,
  yellowBorderGradient: `${imagePath}images/border-layer-2.png`,
  purpleBorderGradient: `${imagePath}images/border-layer-3.png`,
};
