import { imagePath } from "./Constant";

export const assetsObj = {
  logo: `${imagePath}images/logo.png`,
  banner_bg_image: `${imagePath}images/banner-bg.png`,
  banner_image: `${imagePath}images/banner-img-1.png`,
  jquery_icon: `${imagePath}images/jquery_icon.png`,
  mongodb_icon: `${imagePath}images/mongodb-icon.png`,
  android_icon: `${imagePath}images/android_icon.png`,
  java_icon: `${imagePath}images/java_icon .png`,
  logo_first_letter: `${imagePath}images/logo-first-letter.png`,
  client_img1: `${imagePath}images/client-serve-img-1.png`,
  client_img2: `${imagePath}images/client-serve-img-2.png`,
  client_img3: `${imagePath}images/client-serve-img-3.png`,
  learning_system_icon: `${imagePath}icon/e-learning_system_icon.png`,
  employment_meeting_icon: `${imagePath}icon/employment_meeting_icon.png`,
  handshake_agreement_icon: `${imagePath}icon/handshake_agreement_icon.png`,
  share_social_icon: `${imagePath}icon/share_social_icon.png`,
  profile_group_icon: `${imagePath}icon/profile_group_icon.png`,
  hireDevImg1: `${imagePath}images/hire-dev-1.png`,
  hireDevImg2: `${imagePath}images/hire-dev-2.png`,
  blueBorderGradient: `${imagePath}images/border-layer-1.png`,
  yellowBorderGradient: `${imagePath}images/border-layer-2.png`,
  purpleBorderGradient: `${imagePath}images/border-layer-3.png`,
  verifiedUserIcon: `${imagePath}icon/verified_user_account_icon.png`,
  agreementIcon: `${imagePath}icon/agreement_contract_icon.png`,
  locationIcon: `${imagePath}icon/location_icon.png`,
  internetGlobeIcon: `${imagePath}icon/internet_globe_icon.png`,
  rectangleBlueLayer: `${imagePath}images/rectangle-blue-layer.png`,
  rectanglePurpleLayer: `${imagePath}images/rectangle-purple-layer.png`,
  rectangleYellowLayer: `${imagePath}images/rectangle-yellow-layer.png`,
  flashLightningIcon: `${imagePath}icon/flash_lightningicon.png`,
  fileIcon: `${imagePath}icon/file_icon.png`,
  pauseIcon: `${imagePath}icon/pause_icon.png`,
  chartLevelUpIcon: `${imagePath}icon/chart_level_up_icon.png`,
  teamMember1: `${imagePath}images/team-member-1.png`,
  teamMember2: `${imagePath}images/team-member-2.png`,
  muiltipleOpoortunitiesImg: `${imagePath}images/language_chart.png`,
  dottedborder: `${imagePath}images/dotted-line.png`,
  workingEmpImg: `${imagePath}images/working-enployee.png`,
  ellipseBluepink: `${imagePath}images/ellipse-blue-pink.png`,
  ellipseBluePinkSmall: `${imagePath}images/ellipse-blue-pink-small.png`,
  ellipseGreen: `${imagePath}images/ellipse-green.png`,
  ellipseYellow: `${imagePath}images/ellipse-yellow.png`,
  ellipseYellowSmall: `${imagePath}images/ellipse-yellow-small.png`,
  rectangleYellowLayer: `${imagePath}images/rectangle-yellow-layer.png`,
  ellipseSkyblue: `${imagePath}images/ellipse-skyblue.png`,
  facebookIcon: `${imagePath}icon/facebook_icon.png`,
  linkedinIcon: `${imagePath}icon/linkedin_icon.png`,
  youtubeIcon: `${imagePath}icon/youtube_icon.png`,
  instagramIcon: `${imagePath}icon/instagram_icon.png`,
  forDevBg: `${imagePath}images/for-dev-bg.png`,
  girlWithLaptop: `${imagePath}images/girl-with-laptop.png`,
  airbnbLogo: `${imagePath}images/airbnb.png`,
  amazonLogo: `${imagePath}images/amazon.png`,
  dunzoLogo: `${imagePath}images/dunzo.png`,
  googleLogo: `${imagePath}images/google.png`,
  paytmLogo: `${imagePath}images/paytm.png`,
  spotifyLogo: `${imagePath}images/spotify.png`,





  hireTeamBannerImage: `${imagePath}images/hire-team-banner-img.png`,
  checkedIcon: `${imagePath}icon/checked-icon.svg`,
  avatar1: `${imagePath}images/avatar-1.png`,
  avatar2: `${imagePath}images/avatar-2.png`,
  avatar3: `${imagePath}images/avatar-3.png`,
  avatar4: `${imagePath}images/avatar-4.png`,
  talentIcon: `${imagePath}icon/talents-icon.png`,
  hiringModelIcon1: `${imagePath}icon/hiring-model-1.png`,
  hiringModelIcon2: `${imagePath}icon/hiring-model-2.png`,
  hiringModelIcon3: `${imagePath}icon/hiring-model-3.png`,
  hiringModelIcon4: `${imagePath}icon/hiring-model-4.png`,
  developerBG: `${imagePath}images/developer_bg.png`,
  scheduleCallBG: `${imagePath}images/schedule-call-bg.png`,
  scheduleCallImage: `${imagePath}images/schedule-call-image.png`,
  trailIcon: `${imagePath}icon/one-month-trail.svg`,
  moneyBack: `${imagePath}icon/money-back-icon.svg`,
  freeReplacement: `${imagePath}icon/free-replacement.svg`,
  StartTodayBG: `${imagePath}images/start-today-BG.png`,
};
